[project]
name = "mcp-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.11"
dependencies = [
    "mcp[cli]>=1.12.0",
    "psutil>=7.0.0",
    "pytz>=2025.2",
]
